server:
  max-http-header-size: 10240
  tomcat:
    accesslog:
      directory: /data/logs/oauth_server/historyRunLog/access
      enabled: true
      pattern: common
      prefix: auth-server-access
      suffix: .log
      rotate: true
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 0
    timeout: 10000
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: o7r2FkapLfHzbQ==
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 500
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 300
      # 连接池中的最小空闲连接
      min-idle: 100
eureka:
  client:
    serviceUrl:
      defaultZone: http://happymix:20190415@localhost:8761/eureka
  instance:
    lease-expiration-duration-in-seconds: 90  #超过多少时间删除服务
    lease-renewal-interval-in-seconds: 30    #设置心跳时长
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 10000
#微信小程序相关信息
weixin:
  member:
    appid: wx6a9ed7e30ba12e49
    secret: d0f5bbbde4d1f993645b0a6746fb17c8
    # 周美玲本地调试
#    appid: wx3d27cc3626b44fc9
#    secret: 7e880299b445852799b4d0377dec0a18
logging:
  level:
    org.springframework: info
    cn.lfn.gem.dist.mappers: debug
  config: classpath:log4j2-${spring.profiles.active}.yml
