server:
  max-http-header-size: 10240
  tomcat:
    accesslog:
      directory: /data/logs/web
      enabled: true
      pattern: common
      prefix: web-access
      suffix: .log
      rotate: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://gem:123456@gem-dist-eureka:9011/eureka
  instance:
    lease-expiration-duration-in-seconds: 10  #超过多少时间删除服务
    lease-renewal-interval-in-seconds: 5    #设置心跳时长
openapi:
  gem:
    url: http://test.openapi.jpark.vip
    appId: 1003    
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    main:
      allow-bean-definition-overriding: true
  redis:
    database: 0
    timeout: 10000
    # Redis服务器地址
    host: gem-dist-redis
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
  datasource:
    name: dev
    url: jdbc:mysql://gem-dist-mysql8:3306/gem_distribution?allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useSSL=false
    #url: jdbc:mysql://localhost:8636/gem_distribution?allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useSSL=false
    username: root
    password: JFerp2018!v5
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 5
    maxWait: 60000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 2000
    minEvictableIdleTimeMillis: 600000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mapper:
  mappers:
  - tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL
mybatis:
  mapperLocations: classpath:mappers/*.xml
  typeAliasesPackage: cn.lfn.gem.dist.webserver.base.entity
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
feign:
  hystrix:
    enabled: true
pay:
  weixin:
    appid: wx6a9ed7e30ba12e49
    appSecret: d0f5bbbde4d1f993645b0a6746fb17c8
    mchId: 1509776891
    key: 149b8628f007408d99ad32132520caa2
    ip: 39.98.71.133
    notifyUrl: http://test.zberp.fun/wechat-member/api/circleMall/notifyWeiXinPay.do
    refundUrl: http://test.zberp.fun/wechat-member/api/circleMall/notifyWeiXinRefund.do
    sandboxNotifyUrl: http://sjq.zhubaogongyuan.net/wechat-member/api/circleMall/notifyWeiXinPay.do
    certFilePath: /data/happy/wechat_cert/apiclient_cert.p12
    useSandbox: false
swagger-Switch: false
auth-switch: true
# 认证地址 zuul地址转发
auth-server: http://gem-dist-zuul:9001/auth-server
security:
  oauth2:
    client:
      client-id: CLIENT_SYSTEM_PLATFORM
      client-secret: 123456
      access-token-uri: ${auth-server}/oauth/token
    resource:
      id: oauth2_resouce_system_pc
      user-info-uri: ${auth-server}/user
      # 是否使用token info ，两种认证方式选择user info 禁用tokeninfo
      prefer-token-info: false
logging:
  level:
    org.springframework: info
    cn.lfn.gem.dist.mappers: debug
  config: classpath:log4j2-${spring.profiles.active}1.yml
