eureka:
  client:
    serviceUrl:
      defaultZone: http://market:123456@market-sys-eureka:9011/eureka
  instance:
    lease-expiration-duration-in-seconds: 10  #超过多少时间删除服务
    lease-renewal-interval-in-seconds: 5    #设置心跳时长
# 认证地址 zuul地址转发
swagger-Switch: false
auth-switch: true
auth-server: http://market-sys.zberp.net/auth-server
security:
  oauth2:
    client:
      client-id: MARKET_PLATFORM
      client-secret: 123456
      access-token-uri: ${auth-server}/oauth/token
    resource:
      id: oauth2_resouce_pc_market_sys
      user-info-uri: ${auth-server}/user
      # 是否使用token info ，两种认证方式选择user info 禁用tokeninfo
      prefer-token-info: false
swagger2:
  host: market-sys.zberp.net
  oauth-token-Url: http://${swagger2.host}/auth-server/oauth/token     
spring:
  redis:
    database: 0
    timeout: 10000
    # Redis服务器地址
    host: market-sys-redis
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0