server:
  tomcat:
    accesslog:
      directory: /data/logs/wechat/historyRunLog/access
      enabled: true
      pattern: common
      prefix: tools-access
      suffix: .log
      rotate: true
swagger2:
  host: market-sys.zberp.net
  oauth-token-Url: https://${swagger2.host}/auth-server/oauth/token      
eureka:
  client:
    serviceUrl:
      defaultZone: http://market:123456@market-sys-eureka:9011/eureka
  instance:
    lease-expiration-duration-in-seconds: 10  #超过多少时间删除服务
    lease-renewal-interval-in-seconds: 5    #设置心跳时长
spring:
  redis:
    database: 0
    timeout: 10000
    # Redis服务器地址
    host: market-sys-redis
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: boirEYc5Tl8vPZD7pLBGceAY
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
  datasource:
    name: dev
    url: jdbc:mysql://market-sys-mysql8:3306/market-sys?nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useSSL=false
    username: market_sys
    password: boirEYc5Tl8vPZD7pLBGceAY
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      connectionInitSqls: set names utf8mb4
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 5
    maxWait: 60000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 2000
    minEvictableIdleTimeMillis: 600000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL
mybatis:
  mapperLocations: classpath:mappers/*.xml
  typeAliasesPackage: cn.lfn.market.base.base.entity
weixin:
  notifyUrl: https://yukx.ittun.com/wechat/wechat/pay/notifyWeiXinPay.do
  sandboxNotifyUrl: https://yukx.ittun.com/wechat/wechat/pay/notifyWeiXinPay.do
  useSandbox: true
  ip: 192.168.40.136
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000  
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 10000
feign:
  hystrix:
    enabled: true
wechat:
  platform:
    componentAppid: aq
    componentAppSecret: aa