server:
  tomcat:
    accesslog:
      directory: /data/logs/wechat/historyRunLog/access
      enabled: true
      pattern: common
      prefix: tools-access
      suffix: .log
      rotate: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://market:123456@market-sys-eureka:9011/eureka
  instance:
    lease-expiration-duration-in-seconds: 10  #超过多少时间删除服务
    lease-renewal-interval-in-seconds: 5    #设置心跳时长
spring:
  redis:
    database: 0
    timeout: 10000
    # Redis服务器地址
    host: market-sys-redis
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
weixin:
  notifyUrl: http://yukx.ittun.com/wechat/wechat/pay/notifyWeiXinPay.do
  sandboxNotifyUrl: http://yukx.ittun.com/wechat/wechat/pay/notifyWeiXinPay.do
  useSandbox: true
  ip: 192.168.40.136
